#!/usr/bin/env bash
# Rebuilds the WebAssembly engine and stages it into web/.
#
# The wasm binary is base64'd into a .js file rather than shipped as a .wasm
# fetched at runtime, for two reasons: the page must work when opened from
# file:// or a host that blocks cross-origin fetches, and emscripten's own
# SINGLE_FILE mode inlines the binary as a raw string literal whose high bytes
# do not survive charset handling in transit.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(dirname "$here")"
build="$root/build-wasm"

command -v emcmake >/dev/null || { echo "emcmake not found; install emscripten" >&2; exit 1; }

emcmake cmake -B "$build" -S "$root" -DCMAKE_BUILD_TYPE=Release >/dev/null
cmake --build "$build" -j --target even_flop_wasm >/dev/null

cp "$build/even-flop-engine.js" "$here/even-flop-engine.js"

python3 - "$build/even-flop-engine.wasm" "$here/even-flop-wasm.js" <<'PY'
import base64, pathlib, sys

binary = pathlib.Path(sys.argv[1]).read_bytes()
encoded = base64.b64encode(binary).decode("ascii")
pathlib.Path(sys.argv[2]).write_text(
    "// Generated by web/build.sh - do not edit.\n"
    "// The engine's WebAssembly binary, base64 encoded so it survives any\n"
    "// charset handling and needs no separate fetch at runtime.\n"
    f"var EVEN_FLOP_WASM_BASE64 = \"{encoded}\";\n"
)
print(f"wasm {len(binary):,} bytes -> base64 {len(encoded):,} chars")
PY
